services:
  react-app:
    build:
      context: ./react-app
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4318
      - OTEL_RESOURCE_ATTRIBUTES=service.name=react-app,deployment.environment=dev
      - OTEL_TRACES_EXPORTER=otlp
      - OTEL_METRICS_EXPORTER=otlp
    depends_on:
      - spring-app
      - otel-collector

  spring-app:
    build:
      context: ./spring-app
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/mydb
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=password
      - OTEL_EXPORTER_OTLP_PROTOCOL=http/protobuf
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4318
      - OTEL_RESOURCE_ATTRIBUTES=service.name=spring-app,deployment.environment=dev
      - OTEL_TRACES_EXPORTER=otlp
      - OTEL_METRICS_EXPORTER=otlp
    depends_on:
      - mysql
      - loki
      - otel-collector

  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=mydb
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    command: ["--config=/etc/otel-collector-config.yml"]
    volumes:
      - ./otel-collector-config.yml:/etc/otel-collector-config.yml:ro
    ports:
      - "4317:4317"  # gRPC
      - "4318:4318"  # HTTP
      - "9090:9090"  # Prometheus exporter
    depends_on:
      - tempo
      - loki
      - prometheus

  tempo:
    image: grafana/tempo:latest
    command: ["-config.file=/etc/tempo-config.yml"]
    volumes:
      - ./tempo-config.yml:/etc/tempo-config.yml:ro
    ports:
      - "3200:3200"

  loki:
    image: grafana/loki:latest
    command: ["-config.file=/etc/loki-config.yml"]
    volumes:
      - ./loki-config.yml:/etc/loki-config.yml:ro
    ports:
      - "3100:3100"

  prometheus:
    image: prom/prometheus:latest
    command: ["--config.file=/etc/prometheus/prometheus-config.yml"]
    volumes:
      - ./prometheus-config.yml:/etc/prometheus/prometheus-config.yml:ro
      - prometheus-data:/prometheus
    ports:
      - "9091:9090"

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3001:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    depends_on:
      - tempo
      - loki
      - prometheus

networks:
  default:
    name: otel-network
    driver: bridge

volumes:
  mysql-data:
  grafana-data:
  prometheus-data:
